/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clienteProfessor;

import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author gabri_000
 */
public class ClickerOne_CadastroDeQuestoes extends javax.swing.JFrame {

    /**
     * Creates new form ClickerOne_CadastroDeQuestoes
     */
    public ClickerOne_CadastroDeQuestoes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldCodigoAula = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaQuestao = new javax.swing.JTextArea();
        jTextFieldAlternativaA = new javax.swing.JTextField();
        jTextFieldAlternativaB = new javax.swing.JTextField();
        jTextFieldAlternativaC = new javax.swing.JTextField();
        jTextFieldAlternativaD = new javax.swing.JTextField();
        jTextFieldAlternativaE = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jRadioButtonAlternativaA = new javax.swing.JRadioButton();
        jRadioButtonAlternativaB = new javax.swing.JRadioButton();
        jRadioButtonAlternativaC = new javax.swing.JRadioButton();
        jRadioButtonAlternativaD = new javax.swing.JRadioButton();
        jRadioButtonAlternativaE = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de questões");
        setMaximumSize(new java.awt.Dimension(500, 550));
        setMinimumSize(new java.awt.Dimension(500, 550));
        setPreferredSize(new java.awt.Dimension(500, 550));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldCodigoAula.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextFieldCodigoAula.setEnabled(false);
        getContentPane().add(jTextFieldCodigoAula, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 90, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText("Código da aula:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 20));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Enunciado da questão:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jTextAreaQuestao.setColumns(20);
        jTextAreaQuestao.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextAreaQuestao.setRows(5);
        jTextAreaQuestao.setTabSize(2);
        jScrollPane1.setViewportView(jTextAreaQuestao);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 460, -1));

        jTextFieldAlternativaA.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(jTextFieldAlternativaA, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 460, 25));

        jTextFieldAlternativaB.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(jTextFieldAlternativaB, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 460, 25));

        jTextFieldAlternativaC.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(jTextFieldAlternativaC, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 460, 25));

        jTextFieldAlternativaD.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(jTextFieldAlternativaD, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 460, 25));

        jTextFieldAlternativaE.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(jTextFieldAlternativaE, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 460, 25));

        jButton1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton1.setMnemonic('L');
        jButton1.setText("Limpar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 75, -1));

        jButton2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton2.setMnemonic('C');
        jButton2.setText("Concluir");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 470, 80, -1));

        jButton3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton3.setMnemonic('N');
        jButton3.setText("Nova questão");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 470, 110, -1));

        jRadioButtonAlternativaA.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jRadioButtonAlternativaA.setText("Alternativa A:");
        jRadioButtonAlternativaA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAlternativaAActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonAlternativaA, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, 20));

        jRadioButtonAlternativaB.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jRadioButtonAlternativaB.setText("Alternativa B:");
        jRadioButtonAlternativaB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAlternativaBActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonAlternativaB, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, 20));

        jRadioButtonAlternativaC.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jRadioButtonAlternativaC.setText("Alternativa C:");
        jRadioButtonAlternativaC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAlternativaCActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonAlternativaC, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, 20));

        jRadioButtonAlternativaD.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jRadioButtonAlternativaD.setText("Alternativa D:");
        jRadioButtonAlternativaD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAlternativaDActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonAlternativaD, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, 20));

        jRadioButtonAlternativaE.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jRadioButtonAlternativaE.setText("Alternativa E:");
        jRadioButtonAlternativaE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAlternativaEActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonAlternativaE, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, -1, 20));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonAlternativaAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAlternativaAActionPerformed
        if (jRadioButtonAlternativaA.isSelected()) {
            jRadioButtonAlternativaB.setSelected(false);
            jRadioButtonAlternativaC.setSelected(false);
            jRadioButtonAlternativaD.setSelected(false);
            jRadioButtonAlternativaE.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButtonAlternativaAActionPerformed

    private void jRadioButtonAlternativaBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAlternativaBActionPerformed
        if (jRadioButtonAlternativaB.isSelected()) {
            jRadioButtonAlternativaA.setSelected(false);
            jRadioButtonAlternativaC.setSelected(false);
            jRadioButtonAlternativaD.setSelected(false);
            jRadioButtonAlternativaE.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButtonAlternativaBActionPerformed

    private void jRadioButtonAlternativaCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAlternativaCActionPerformed
        if (jRadioButtonAlternativaC.isSelected()) {
            jRadioButtonAlternativaA.setSelected(false);
            jRadioButtonAlternativaB.setSelected(false);
            jRadioButtonAlternativaD.setSelected(false);
            jRadioButtonAlternativaE.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButtonAlternativaCActionPerformed

    private void jRadioButtonAlternativaDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAlternativaDActionPerformed
        if (jRadioButtonAlternativaD.isSelected()) {
            jRadioButtonAlternativaA.setSelected(false);
            jRadioButtonAlternativaB.setSelected(false);
            jRadioButtonAlternativaC.setSelected(false);
            jRadioButtonAlternativaE.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButtonAlternativaDActionPerformed

    private void jRadioButtonAlternativaEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAlternativaEActionPerformed
        if (jRadioButtonAlternativaE.isSelected()) {
            jRadioButtonAlternativaA.setSelected(false);
            jRadioButtonAlternativaB.setSelected(false);
            jRadioButtonAlternativaC.setSelected(false);
            jRadioButtonAlternativaD.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButtonAlternativaEActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Deseja realmente limpar todos os campos?", "Confirmação", 1, 1) == JOptionPane.YES_OPTION) {
            jTextAreaQuestao.setText("");
            jTextFieldAlternativaA.setText("");
            jTextFieldAlternativaB.setText("");
            jTextFieldAlternativaC.setText("");
            jTextFieldAlternativaD.setText("");
            jTextFieldAlternativaE.setText("");
            jRadioButtonAlternativaA.setSelected(false);
            jRadioButtonAlternativaB.setSelected(false);
            jRadioButtonAlternativaC.setSelected(false);
            jRadioButtonAlternativaD.setSelected(false);
            jRadioButtonAlternativaE.setSelected(false);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClickerOne_CadastroDeQuestoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClickerOne_CadastroDeQuestoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClickerOne_CadastroDeQuestoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClickerOne_CadastroDeQuestoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClickerOne_CadastroDeQuestoes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRadioButtonAlternativaA;
    private javax.swing.JRadioButton jRadioButtonAlternativaB;
    private javax.swing.JRadioButton jRadioButtonAlternativaC;
    private javax.swing.JRadioButton jRadioButtonAlternativaD;
    private javax.swing.JRadioButton jRadioButtonAlternativaE;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaQuestao;
    private javax.swing.JTextField jTextFieldAlternativaA;
    private javax.swing.JTextField jTextFieldAlternativaB;
    private javax.swing.JTextField jTextFieldAlternativaC;
    private javax.swing.JTextField jTextFieldAlternativaD;
    private javax.swing.JTextField jTextFieldAlternativaE;
    private javax.swing.JTextField jTextFieldCodigoAula;
    // End of variables declaration//GEN-END:variables
}
