/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clienteAluno;

/**
 *
 * @author gabri_000
 */
public class ClickerOne_TelaRespostas extends javax.swing.JFrame {

    /**
     * Creates new form ClickerOne_TelaRespostas
     */
    public ClickerOne_TelaRespostas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaQuestao = new javax.swing.JTextArea();
        jRadioButtonAlternativaA = new javax.swing.JRadioButton();
        jRadioButtonAlternativaB = new javax.swing.JRadioButton();
        jRadioButtonAlternativaC = new javax.swing.JRadioButton();
        jRadioButtonAlternativaD = new javax.swing.JRadioButton();
        jRadioButtonAlternativaE = new javax.swing.JRadioButton();
        jButtonProximoEConcluir = new javax.swing.JButton();
        jButtonAnterior = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Questões");
        setMaximumSize(new java.awt.Dimension(550, 550));
        setMinimumSize(new java.awt.Dimension(550, 550));
        setPreferredSize(new java.awt.Dimension(550, 550));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText("Questão:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 25, -1, 25));

        jTextAreaQuestao.setEditable(false);
        jTextAreaQuestao.setColumns(20);
        jTextAreaQuestao.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextAreaQuestao.setRows(5);
        jScrollPane1.setViewportView(jTextAreaQuestao);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 490, 120));

        jRadioButtonAlternativaA.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jRadioButtonAlternativaA.setText("A) + resposta do \"banco\"");
        jRadioButtonAlternativaA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAlternativaAActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonAlternativaA, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, 25));

        jRadioButtonAlternativaB.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jRadioButtonAlternativaB.setText("B) + resposta do \"banco\"");
        jRadioButtonAlternativaB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAlternativaBActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonAlternativaB, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, 25));

        jRadioButtonAlternativaC.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jRadioButtonAlternativaC.setText("C) + resposta do \"banco\"");
        jRadioButtonAlternativaC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAlternativaCActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonAlternativaC, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, 25));

        jRadioButtonAlternativaD.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jRadioButtonAlternativaD.setText("D) + resposta do \"banco\"");
        jRadioButtonAlternativaD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAlternativaDActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonAlternativaD, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, 25));

        jRadioButtonAlternativaE.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jRadioButtonAlternativaE.setText("E) + resposta do \"banco\"");
        jRadioButtonAlternativaE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAlternativaEActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonAlternativaE, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, 25));

        jButtonProximoEConcluir.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButtonProximoEConcluir.setMnemonic('P');
        jButtonProximoEConcluir.setText("Próximo >>");
        getContentPane().add(jButtonProximoEConcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 460, -1, 25));

        jButtonAnterior.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButtonAnterior.setMnemonic('A');
        jButtonAnterior.setText("<< Anterior");
        getContentPane().add(jButtonAnterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, -1, 25));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonAlternativaAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAlternativaAActionPerformed
        if (jRadioButtonAlternativaA.isSelected()) {
            jRadioButtonAlternativaB.setSelected(false);
            jRadioButtonAlternativaC.setSelected(false);
            jRadioButtonAlternativaD.setSelected(false);
            jRadioButtonAlternativaE.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButtonAlternativaAActionPerformed

    private void jRadioButtonAlternativaBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAlternativaBActionPerformed
        if (jRadioButtonAlternativaB.isSelected()) {
            jRadioButtonAlternativaA.setSelected(false);
            jRadioButtonAlternativaC.setSelected(false);
            jRadioButtonAlternativaD.setSelected(false);
            jRadioButtonAlternativaE.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButtonAlternativaBActionPerformed

    private void jRadioButtonAlternativaCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAlternativaCActionPerformed
        if (jRadioButtonAlternativaC.isSelected()) {
            jRadioButtonAlternativaA.setSelected(false);
            jRadioButtonAlternativaB.setSelected(false);
            jRadioButtonAlternativaD.setSelected(false);
            jRadioButtonAlternativaE.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButtonAlternativaCActionPerformed

    private void jRadioButtonAlternativaDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAlternativaDActionPerformed
        if (jRadioButtonAlternativaD.isSelected()) {
            jRadioButtonAlternativaA.setSelected(false);
            jRadioButtonAlternativaB.setSelected(false);
            jRadioButtonAlternativaC.setSelected(false);
            jRadioButtonAlternativaE.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButtonAlternativaDActionPerformed

    private void jRadioButtonAlternativaEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAlternativaEActionPerformed
        if (jRadioButtonAlternativaE.isSelected()) {
            jRadioButtonAlternativaA.setSelected(false);
            jRadioButtonAlternativaB.setSelected(false);
            jRadioButtonAlternativaC.setSelected(false);
            jRadioButtonAlternativaD.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButtonAlternativaEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClickerOne_TelaRespostas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClickerOne_TelaRespostas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClickerOne_TelaRespostas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClickerOne_TelaRespostas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClickerOne_TelaRespostas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnterior;
    private javax.swing.JButton jButtonProximoEConcluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButtonAlternativaA;
    private javax.swing.JRadioButton jRadioButtonAlternativaB;
    private javax.swing.JRadioButton jRadioButtonAlternativaC;
    private javax.swing.JRadioButton jRadioButtonAlternativaD;
    private javax.swing.JRadioButton jRadioButtonAlternativaE;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaQuestao;
    // End of variables declaration//GEN-END:variables
}
